import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import AuthProvider from "@/services/AuthProvider";

export const metadata: Metadata = {
  title: "Private Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
