import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { ClientProviders } from "@/services/ClientProviders";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Private Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body>
        <Suspense fallback={<div>Loading...</div>}>
          <ClientProviders>
            <Navbar />
            {children}
          </ClientProviders>
        </Suspense>
      </body>
    </html>
  );
}